# Generated by Django 4.1.3 on 2022-12-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groceries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grocery_name', models.CharField(max_length=30)),
                ('grocery_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30)),
                ('task_responsible', models.CharField(max_length=30)),
                ('task_creation_date', models.DateTimeField(auto_now=True)),
                ('task_update_date', models.DateTimeField(auto_now_add=True)),
                ('task_deadline', models.DateTimeField()),
                ('task_description', models.TextField()),
                ('task_email', models.EmailField(max_length=254)),
                ('task_photo', models.URLField()),
                ('task_attachment', models.FileField(upload_to='')),
                ('task_accepted', models.BooleanField()),
            ],
        ),
    ]
