# Generated by Django 4.1.3 on 2022-12-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_groceries_grocery_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_responsible',
            field=models.CharField(choices=[('DZ', 'Daniel'), ('MZ', 'Maxi'), ('BA', 'Boryana'), ('AZ', 'Adriana')], max_length=30),
        ),
    ]
