# Generated by Django 4.1.3 on 2022-12-09 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_games_alter_groceries_options_alter_tasks_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GamesAdmin',
        ),
    ]
