# Generated by Django 4.1.3 on 2022-12-14 12:37

from django.db import migrations, models
import zorov_hub.main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_games_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='game_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_name',
            field=models.CharField(max_length=30, validators=[zorov_hub.main_app.validators.validate_text]),
        ),
    ]
