# Generated by Django 4.1.3 on 2022-12-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_games_game_image_alter_games_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
