# Generated by Django 4.1.3 on 2022-12-19 12:35

from django.db import migrations, models
import zorov_hub.main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_games_game_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=30, validators=[zorov_hub.main_app.validators.validate_profile_name])),
                ('profile_type', models.CharField(choices=[('noob', 'noob'), ('pro', 'pro'), ('gigachad', 'gigachad')], max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='games',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='SLUG'),
        ),
    ]
